### ISSUE TITLE
A "templates/index.html" file should exist?

### ISSUE THREAD

**Issue by tetsuyasodo** [kongou-ae/ConvertTo-AzHtml#5]
Thank you for developing a great tool. It would help me a lot with large Azure environment.

When I run the command fist time, I got the following error message.
Do I have this file before running the command? I'm afraid I don't have this from 'git clone'.
If I'm wrong with any prerequisites, kindly tell me. Thanks in advance.

```
PS /home/tetsuya_sodo/ConvertTo-AzHtml> ./ConvertTo-AzHtml.ps1
Get-Content: /home/tetsuya_sodo/ConvertTo-AzHtml/ConvertTo-AzHtml.ps1:3
Line |
   3 |  $rootHtml = Get-content .\templates\index.html
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path '/home/tetsuya_sodo/ConvertTo-AzHtml/templates/index.html' because it does not exist.

PS /home/tetsuya_sodo/ConvertTo-AzHtml>
```

**Comment by kongou-ae** [comment]
@tetsuyasodo 

Thank you for trying my tool.

This file should be in the folder which you cloned. The root cause of this issue is I didn't push index.html due to a wrong .gitignore. I pushed the new .gitignore, and confirmed this repo contains index.html from the beginning. Could you try again, please?

Best regards.

**Comment by tetsuyasodo** [comment]
Thanks for your quick reply.
This time I could run the command without any errors and get the output html file.
I'll share this nice tool within my reach, but you may introduce it to Azure community 👍
